dist: xenial
sudo: required
language: node_js
node_js:
- lts/*
install:
- wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
- sudo dpkg -i hugo*.deb
script:
- yarn
- hugo version
- hugo
before_deploy:
- openssl aes-256-cbc -K $encrypted_faafb99445c4_key -iv $encrypted_faafb99445c4_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip-cleanup: true
  script: rsync -r --quiet --delete-after ${TRAVIS_BUILD_DIR}/public/* ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master
env:
  global:
  - PRODUCTION=true
  - HUGO_RELEASE=0.65.2
  - secure: jjn/TTVHkQvAqQrYTEM5vqsrDKHcAOOwUgeW/vwGJmoiwyF/luPaElnRlWGSC1GXRx4RG+PswTur0KfbYa9V6ZIqtDI7tHvhGevSp5xhPqcqX1a/erHYsPC+3uPYnQYdO+VLEOTolQRPw9Bg0gDIin3w0AZQG4EGWRem/DAQPpVUNtiRgrxAtlLTRD2h0KzUiOaXnwuFxIXiKTlm+5folnwlzzZVetsM4T6dy9LOy/uwrHPGO8B5xVNd4VYm0VAkYjUiXy1kmuF821hbh/1rSnlvofie6h/aEwolTnuXZHRjoxYO9eIxuw0MXujQQEps675B/STt2biOEeBqSM2G0GWen5FXcl21d21SzI8pp8EWNr3csPshWi7jS/7gVOi5j9m7cd3FeSn8bTyxwupl7wRabZW3XB7Pu0V6xf2EwqSCN4k/3QObDBcNDZ5oKqgzoBN5URMw2tCpbNWHYS6oGuq0Nwd7xtMjpxYl/gJM3J/RsHodFR/EDaZKXObu2O7kScOBVoHFlTkHRMDIBQaRse7BXgVp0F/GkRNb6JKwaPG+RVFAHS7FtsMiMtODxLRb356UWhA+Xwl74eK+AZ4ZxI4rqf1v3Ql15nlmas61iDE5x3zVsKbecWaBblR0mNTtsAExHlOgl0Z71OdEUu89Dumd5OmBhB36RR79h1y454s=
  - secure: EBxm8DSrfoMqw0I0N3tLiuVkOYvPZHtmo0lsCiKvRNT4gyaQaaHrG4YixeoZK0gSergYZBK7kIvInCz+OxS54k19uHkpQxdJEOJS/QereMtd5AhFsYqQR5t1239ZRd4FyqQmkv5G4mzGGQpVYPmINErj/8uAKoJFaUv7xFHH60BpKoRN/77AmujEkuUzSHUrDykUQSTCAjIW6/05yjJAl2Ew0qafPgcmTgVe4ZqcKxHeMqR/79sCsSpVJRGvPmxRhAz4Hz+35Cj0wsflNtMLL5dEFNf2IMsrG/LLwO6fXsyZN/rSF4Is4xg29/r0+rL08U5y2IgHD12fzJ1hV47zOyDtLumIAamN4mcUAjWGuedLcz+QrJDCm0RObOct5K2H0ZCYAjh8J0zSxZ1prSzjtY1CKd/1YzMNVNuj5iordei5Bfg47xGO1ePN6DiGJJzlOJLGbNVPSv4u7sze1d57ZnfjB59Qx1SZW2oSbuqOeFQnqJ4zmIPUCKOKaP1LANuYRiQ8eexBL/vo/+e1TXLzaZ9dTJ+5fX7ec9rxfYHUnpWp5zrqniVsHpBkozmFpPo1GUxT+S6GP0SyLlf7L3RSEj7RV942UMxd39bZlygw6jROMTM+Dp7OUBEUyMAxDCzeMvEMvkbU7bwcqf+ixdQniS4GV/NWhY4XTACCC97DXk0=
  - secure: fWfqlvTldv43AfcdK9FQkniR9Oeox4UhOgfeiqzWv7F01gj7ipgr3W1vC9YDX4DIt4JJin4iRCRqXy6S2Dbnq4Ny8miPk6ULTYd9loX2BgRRn0v3j1Ku8GgBMrRIeu+JSdggYxW8u3LQFi4HBeOt4s7w+mhrb6ROtTrQA2ytuqe8baD8iI+VzMJG7JxkenTNMuhuTpLuIm0YdJMDi+OEJO4rsbZwfKByI2XC3uqq7A+Hhc43PSfrOKhDVB/R6csARMY7GZYM0xV6PQCM2tOs8xbwiZTKTghQGuUzDez0r3yPQ7f0vv1Kk91cwmu2cCT/3MPGVWzKCRXVMIwVrDnXbtmznHre7kP8hFa7D5QYT5MH7BBa6udkRHQBUbRmLG6RSI73yczOUyOO8RT2bErUWi4jTBSPQepXRNlmFL1BzIp3ABc/lW5GZAZyFCXYP4TrLVJKZVk0ZwWCMgpyfm9u3jf48WRA23gnvHJjH6yGHrNjhvS43NMQ9KJw2ylESIfIVr8nihwygN9ONbHIXQuJvDLW+nxVbbriAEnI148AaQC//YBHdnttMQMkxQ7VcjSwWzuKlcsMrysSkB0yyl7EFokN2uS8vAQjTjhddS9z3p1PxGDZ+tya3qt0Hg9TsPcSGK1MI/z3qw9xYYqLgsyIPrReKiNkUsVQIAzFq9aLe2c=